version: '3.8'

services:
  mysqldb:
    container_name: mysqldocker4
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: cars
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - spring-mysql-net

  spring-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: spring-app
    depends_on:
      mysqldb:
        condition: service_healthy
    ports:
      - "8000:8000"  # Changed to match your EXPOSE 8000
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/cars?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_DATABASE_PLATFORM: org.hibernate.dialect.MySQL5InnoDBDialect
      SPRING_JPA_GENERATE_DDL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop
      SPRING_DATA_REST_BASEPATH: /api
    networks:
      - spring-mysql-net

networks:
  spring-mysql-net:
    driver: bridge

volumes:
  mysql_data: